### ISSUE TITLE
Debug callback?

### ISSUE THREAD

**Issue by atesgoral** [nrkn/hrm-cpu#18]
Good job on adding level validation! I guess you beat me to it. I was going to suggest adding a debug callback argument to `hrm()` so that level validation could be done by consumers that are interested in it (that way, the cpu would remain agnostic of levels). It would also allow the implementation of rendered/loggers. What do you think?

**Comment by nrkn** [comment]
Leaving aside implementation, how would you imagine calling it, can you give me an example?

I'm currently thinking about how to most cleanly implement starting/stopping/stepping etc. and I think from an implementation POV there is some overlap here - I want this to make a 2nd project hrm-cpu-web (or a better name) which would be a babel+browserified version + html frontend

Also I think passing the level into hrm is the wrong approach, I think I should get the consumer to construct an options object from the level and pass that in instead, thoughts?

Also I'm wondering if we shouldn't have an hrm-schema project that would export an array of schema for various things? That way your level-schema could be composed of those schema via $ref and I could use various parts of it for things as well?

Edit: not URI $ref, just plain string ids like "level" and then register them all with tv4 before doing validation

**Comment by atesgoral** [comment]
Perhaps something like:

```
var steps = 0;

hrm(source, tiles, function (lineNum, command, arg) {
    console.log(lineNum, command, arg);
    steps++;
});
```

Program size can also be determined externally by using `compile()` and looking at the array's length.

And perhaps `hrm` can be used as a namespace to naturally expose both `htm.compile()` and `hrm.run()`. And `hrm.run()` could be polymorphic:

```
var program = hrm.compile(source);
hrm.run(program);
// or:
hrm.run(source2);
```

But I digress...

My main point is, perhaps the runtime doesn't need anything but initial tiles. All other level-specific constraints could be enforced by the user in a debug callback.

Furthermore, to enable step-by-step debugging, perhaps:

```
hrm.run(source, tiles, function (line, cmd, arg, resume) {
    resume();
});
```

Or maybe no need for the extra arg since `this` could be used: `this.resume()` etc.

I had created the hrm-level-data schema just for CI for that tiny little project and didn't ever mean to define a universal schema that could be used to enforce level formats elsewhere. So perhaps keeping things decoupled from hrm-level-data schema might keep things leaner.

**Comment by nrkn** [comment]
Yeah I'm going to decouple by requiring you to pass in options object instead of a level - soon!

And also yeah I can add a callback, just want to have a think about it for a little while

For your first case, checking program length, I've moved the parser to a separate project:

https://github.com/nrkn/hrm-parser

**Comment by nrkn** [comment]
For v0.2.0:

``` javascript
var program = Hrm( source, options )

const logNext = () => {
  program.step( ( err, state ) => {
    if( err ){
      console.error( err )
      return
    }

    console.log( state.lineNumber, state.instr, state.arg )

    if( !state.running ){
      console.log( 'Done!' )
      console.log( state.outbox )

      return
    }

    logNext()
  })
}

const run = () => {
  program.run( ( err, outbox ) => {
    if( err ){
      console.error( err )
      return
    }

    console.log( outbox )
  })
}

const runVerbose = () => {
  program.run( ( err, outbox, state ) => {
    if( err ){
      console.error( err )
      return
    }

    console.log( state )
  })
}

logNext()
run()
runVerbose()
```

**Comment by nrkn** [comment]
And if no callback passed:

``` javascript
const outbox = program.run()

const state = program.step()
```

**Comment by sixlettervariables** [comment]
I'm looking at an `EventEmitter` approach for **hrmsandbox**, but had also considered a `connect`-style callback with `next` and `back` available (rather than direct instruction pointer manipulation).

I'd emit a `preTick` and `tick` event with a copy of the current internal state. I'd also add an `error` event, and perhaps some other events to aid in animations on the browser side (or debugging on the client side).

**Comment by nrkn** [comment]
Yeah, I considered using events, and also streams. I feel like streams would be neat, then it would be easy to for example pipe the output of one program into the input of another. But I'm trying to keep it as simple and lightweight as possible, so in the end I decided on the above

**Comment by nrkn** [comment]
@atesgoral 0.2.0 should have all the things you wanted :)
- pass a program instead of source
- run/step with callback (optional, can run sync too)
- options to setup constraints etc.
- decoupled from levels

**Comment by atesgoral** [comment]
:+1: awesome! I'll integrate at the first chance.

**Comment by atesgoral** [comment]
Integrated.

**Comment by nrkn** [comment]
Awesome, I'm just cloning now to have a play

**Comment by nrkn** [comment]
When I run it, the steps count doesn't seem to match the file names?

Am I counting them wrongly, or do you have some insight into what it could be otherwise?

**Comment by nrkn** [comment]
Ah it may be that the game uses multiple tests and averages the results, yes?

**Comment by atesgoral** [comment]
Yes, the current validation task just runs the first example from hrm-level-data. I'm in the process of running 1000 i/o pairs generated via hrm-level-inbox-generator/hrm-level-outbox-generator for each level to get the average speed.

**Comment by nrkn** [comment]
Apologies as I haven't had a chance to play with the generators yet, but won't the averages be different unless they use the same suite as the program? Or am I being a dunderhead and the way you've implemented accounts for that? Didn't get enough sleep last night!

**Comment by atesgoral** [comment]
Finished an early cut of averaging the step count for 100 random inbox runs: https://travis-ci.org/atesgoral/hrm-solutions

For some solutions, the average steps reported by the game and what I calculate are wildly different. The issue could be with my assumptions about inbox generation criteria. Those could be incrementally fine-tuned to match the game better. Also, I could try running a different random number generator and always start with the same seed to keep measurements deterministic.
