### ISSUE TITLE
Overload / new property to support parsed programs?

### ISSUE THREAD

**Issue by atesgoral** [nrkn/hrm-cpu#28]
Especially for benchmarking loops, it would be nice to be able to parse a program once using hrm-parser and pass the result into hrm-cpu either through the source option or a new option like program.

**Comment by nrkn** [comment]
Already supported, anywhere you can pass a string source you can also pass a pre-parsed array :)

https://github.com/nrkn/hrm-cpu/blob/master/parse-args.js
