### ISSUE TITLE
Code doesn't match example

### ISSUE THREAD

**Issue by LRFLEW** [nrkn/hrm-cpu#9]
The example code in usage has `const floor = {9: 0}`, but the code is expecting something like `const floor = {tiles: {9: 0}}`. Either the code or the example should be changed to match the other.

**Comment by nrkn** [comment]
Thanks! There's a line where it's supposed to be tiles[ key ] but is instead floor.tiles[ key ], will get onto this shortly

**Comment by nrkn** [comment]
To clarify, both `{ 9: 0 }` and `{ tiles: { 9: 0 } }` are supposed to work
